# Generated by Django 3.2 on 2022-08-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_actividad_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('zona', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='animador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.animador'),
        ),
    ]
