# Generated by Django 3.2 on 2022-08-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_alter_actividad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='animador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.animador'),
        ),
    ]
