# Generated by Django 3.2 on 2022-08-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_actividad_animador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='animador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.animador'),
        ),
        migrations.AlterField(
            model_name='animador',
            name='zona',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
